_format_version: "3.0"

services:
  - name: user-service
    url: http://user-service:3001
    plugins:
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
      - name: cors
        config:
          origins:
            - "http://localhost:5173"
            - "https://farmconnect.com"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
          headers:
            - Accept
            - Authorization
            - Content-Type
            - X-Requested-With
          credentials: true
      - name: request-size-limiting
        config:
          allowed_payload_size: 10
      - name: response-transformer
        config:
          add:
            headers:
              - "X-Content-Type-Options: nosniff"
              - "X-Frame-Options: DENY"
              - "X-XSS-Protection: 1; mode=block"
              - "Strict-Transport-Security: max-age=31536000; includeSubDomains"

  - name: product-service
    url: http://product-service:3002
    plugins:
      - name: rate-limiting
        config:
          minute: 200
          hour: 2000
      - name: cors
        config:
          origins:
            - "http://localhost:5173"
            - "https://farmconnect.com"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
          headers:
            - Accept
            - Authorization
            - Content-Type
            - X-Requested-With
          credentials: true

  - name: order-service
    url: http://order-service:3003
    plugins:
      - name: rate-limiting
        config:
          minute: 50
          hour: 500
      - name: cors
        config:
          origins:
            - "http://localhost:5173"
            - "https://farmconnect.com"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
          headers:
            - Accept
            - Authorization
            - Content-Type
            - X-Requested-With
          credentials: true

  - name: payment-service
    url: http://payment-service:3004
    plugins:
      - name: rate-limiting
        config:
          minute: 20
          hour: 200
      - name: cors
        config:
          origins:
            - "http://localhost:5173"
            - "https://farmconnect.com"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
          headers:
            - Accept
            - Authorization
            - Content-Type
            - X-Requested-With
          credentials: true

routes:
  - name: user-routes
    service: user-service
    paths:
      - /api/users
      - /api/auth

  - name: product-routes
    service: product-service
    paths:
      - /api/products

  - name: order-routes
    service: order-service
    paths:
      - /api/orders

  - name: payment-routes
    service: payment-service
    paths:
      - /api/payments

plugins:
  - name: prometheus
    config:
      per_consumer: true